dist: bionic
os: linux
language: c

compiler:
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'deb http://openresty.org/package/ubuntu bionic main'
        key_url: https://openresty.org/package/pubkey.gpg
    packages:
      - lua5.1
      - lua5.1-dev
      - luarocks
      - git
      - libssl-dev
      - build-essential
      - wget
      - unzip
      - openresty
      - openresty-resty

cache:
  apt: true
  directories:
    - /home/travis/.luarocks/

install:
  - luarocks show lua-cjson || luarocks --local install lua-cjson
  - luarocks show luaposix || luarocks --local install luaposix
  - luarocks show telescope || luarocks --local install https://raw.githubusercontent.com/jdesgats/telescope/master/rockspecs/telescope-scm-1.rockspec
  - luarocks show luasocket || luarocks --local install luasocket
  - luarocks show luasec || luarocks --local install luasec
  - luarocks show luacheck || luarocks --local install luacheck

script:
  - export PATH=${HOME}/.luarocks/bin:${PATH}
  - export LUA_PATH='/usr/share/lua/5.1/?.lua;;'
  - make test
